config/routes.rb
Rails.application.routes.draw do
  mount ActiveStorageDB::Engine => '/active_storage_db'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up", to: "rails/health#show", as: :rails_health_check

  get 'search', to: 'search#index'

  resources :manufacturers, only: [], param: :slug do
    resources :discs, only: [:show], param: :slug
  end

  namespace :admin do
    resources :discs

    get 'login', to: 'login#new'
    post 'login', to: 'login#create'
  end

  get 'admin', to: 'admin/discs#index'

  root "home#index"

  if Rails.env.production?
    get '*path', to: 'home#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/capitalizable.rb
module Capitalizable
  extend ActiveSupport::Concern

  included do
    before_save :capitilize_name
  end

  private

  def capitilize_name
    self.name = name.titleize
  end
end

app/models/disc.rb
class Disc < ApplicationRecord
  include PgSearch::Model
  include Capitalizable

  pg_search_scope :search_by_name,
                  associated_against: { manufacturer: :name },
                  against: :name,
                  order_within_rank: 'discs.slug ASC',
                  using: { tsearch: { prefix: true } }

  has_one_attached :image

  belongs_to :manufacturer

  validates :image_url,
            format: URI::DEFAULT_PARSER.make_regexp(%w[http https]),
            allow_blank: true
  validates :name, presence: true, uniqueness: { scope: :manufacturer_id }
  validates :slug, presence: true, uniqueness: { scope: :manufacturer_id }
  validates_presence_of :speed,
                        :glide,
                        :turn,
                        :fade

  enum category: %i[distance_driver control_driver hybrid_driver fairway_driver midrange approach putter]
  enum stability: %i[very_overstable overstable stable understable very_understable]

  def image_file_name
    image.blob.filename.to_s if image.attached?
  end
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  include Capitalizable

  has_many :discs
  validates :name, presence: true, uniqueness: true
  validates :slug, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    layout 'admin'

    before_action :authenticate_admin!

    private

    def authenticate_admin!
      redirect_to admin_login_path unless current_user.present?
    end

    def current_user
      @current_user ||= User.find_by_id(session[:user_id])
    end
  end
end

app/controllers/admin/discs_controller.rb
module Admin
  class DiscsController < Admin::BaseController
    def index
      @data = Disc.includes(:manufacturer)
                  .order('manufacturers.name ASC, discs.name ASC')
                  .group_by(&:manufacturer)
    end

    def create
      @disc = Disc.new(permitted)
      if @disc.save
        flash[:notice] = "#{@disc.name} created successfully."
        redirect_to admin_discs_path
      else
        flash.now[:error] = @disc.errors.full_messages[0]
        render :new, status: :unprocessable_entity
      end
    end

    def new
      @disc = Disc.new
    end

    # rubocop:disable Metrics/AbcSize
    def update
      @disc = Disc.find(params[:id])
      if @disc.update(permitted)
        flash[:notice] = "#{@disc.name} updated successfully."
        redirect_to admin_discs_path
      else
        flash.now[:error] = @disc.errors.full_messages[0]
        render :edit, status: :unprocessable_entity
      end
    end
    # rubocop:enable Metrics/AbcSize

    def destroy
      Disc.find(params[:id]).destroy!
      flash[:notice] = 'Successfully deleted disc.'
      redirect_to admin_discs_path
    end

    def edit
      @disc = Disc.find(params[:id])
    end

    private

    def permitted
      params.require(:disc).permit(:name, :slug, :speed, :glide, :turn,
                                   :fade, :image_url, :category, :stability,
                                   :manufacturer_id)
    end
  end
end

app/controllers/admin/login_controller.rb
module Admin
  class LoginController < Admin::BaseController
    skip_before_action :authenticate_admin!
    def new
      redirect_back(fallback_location:) if User.exists?(session[:user_id])
      session[:user_id] = nil
    end

    def create
      @user = User.find_by(username: permitted[:username])
      if @user&.authenticate(permitted[:password])
        session[:user_id] = @user.id
        redirect_to admin_discs_path
      else
        flash.now[:error] = 'Invalid username or password'
        render :new
      end
    end

    private

    def permitted
      params.permit(:username, :password)
    end

    def fallback_location
      admin_discs_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private

  def record_not_found
    render file: 'public/404.html', status: :not_found
  end
end

app/controllers/discs_controller.rb
class DiscsController < ApplicationController
  def show
    @manufacturer = Manufacturer.find_by!(slug: params[:manufacturer_slug])
    @disc = @manufacturer.discs.find_by!(slug: params[:slug])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @search_results = SearchService.call(query: params[:q],
                                         sort_by: params[:sort_by],
                                         sort_direction: params[:sort_direction])

    render layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/discs/edit.html.erb
<%= render Discs::FormComponent.new(disc: @disc) %>

app/views/admin/discs/index.html.erb
<div class="flex flex-col">
  <div class="text-right mt-2 mr-2">
    <%= link_to 'Create Disc', new_admin_disc_path, class: 'py-3 px-10 rounded bg-poly-green text-white font-bold text-center hover:bg-cadet-gray hover:text-black' %>
  </div>
  <table class="table-auto mt-10">
    <tr class="text-left">
      <th class="p-1">ID</th>
      <th class="p-1">Name</th>
      <th class="p-1">Slug</th>
      <th class="p-1">Speed</th>
      <th class="p-1">Glide</th>
      <th class="p-1">Turn</th>
      <th class="p-1">Fade</th>
      <th class="p-1">Stability</th>
      <th class="p-1">Category</th>
    </tr>
    <% @data.each do |manufacturer, discs| %>
      <tr class="bg-columbia-blue text-black text-3xl"><th colspan='14' class="py-4 border border-white"><%= manufacturer.name %></th></tr>
      <%= render Admin::Discs::RowComponent.with_collection(discs) %>
    <% end %>
  </table>
</div>

app/views/admin/discs/new.html.erb
<%= render Discs::FormComponent.new(disc: @disc) %>

app/views/admin/login/new.html.erb
<h1 class="text-center text-4xl">Login</h1>
<%= form_with url: admin_login_path, data: { turbo: false } do |f| %>
  <div class="flex flex-col items-center justify-center mt-5">
    <%= f.label :username, class: 'mt-4 text-xl' %>
    <%= f.text_field :username, class: 'p-1 border border-gray-600 rounded-lg bg-gray-700 border-gray-600 placeholder-columbia-blue focus:border-columbia-blue focus:ring-columbia-blue text-columbia-blue', required: true %>
    <%= f.label :password, class: 'mt-4 text-xl' %>
    <%= f.password_field :password, class: 'p-1 border border-gray-600 rounded-lg bg-gray-700 border-gray-600 placeholder-columbia-blue focus:border-columbia-blue focus:ring-columbia-blue text-columbia-blue', required: true %>
    <%= f.submit 'Login', class: 'bg-columbia-blue hover:bg-poly-green text-black hover:text-columbia-blue font-bold py-2 px-4 rounded-lg mt-5' %>
  </div>
<% end %>

app/views/discs/show.html.erb
<%= render Discs::SearchComponent.new %>
<%= render DiscComponent.new(disc: @disc) %>

app/views/home/index.html.erb
<%= render Discs::SearchComponent.new %>
<%= turbo_frame_tag :search_results %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Discpedia Admin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'tailwind', 'inter-font', "data-turbo-track": 'reload' %>

    <%= stylesheet_link_tag 'application', "data-turbo-track": 'reload' %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
  </head>

  <body class="bg-poly-green">
    <main class="text-white">
      <%= link_to admin_discs_path do %>
        <h1 class="text-5xl text-center text-white my-12">Discapedia Admin</h1>
      <% end %>

      <%= render Admin::NoticeComponent.new(flash:) %>

      <div class="p-4 bg-air-force-blue rounded w-5/6 mx-auto">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Discapedia</title>
    <meta name="description" content="A Disc Golf flight number encyclopedia. Quickly find and view disc golf discs by name or manufacturer.">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'tailwind', 'inter-font', "data-turbo-track": 'reload' %>

    <%= stylesheet_link_tag 'application', "data-turbo-track": 'reload' %>
    <%= favicon_link_tag 'fav.png' %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
  </head>

  <body class="bg-air-force-blue">
    <%= render partial: 'shared/navbar' %>

    <main class="container px-3 md:px-12 mx-auto mt-28">
      <%= yield %>
    </main>
  </body>
</html>

app/views/login/new.html.erb
<h1 class="text-center text-4xl">Login</h1>
<%= form_with url: login_path do |f| %>
  <div class="flex flex-col items-center justify-center mt-5">
    <%= f.label :username, class: 'mt-4 text-xl' %>
    <%= f.text_field :username, class: 'p-1 border border-gray-600 rounded-lg bg-gray-700 border-gray-600 placeholder-columbia-blue focus:border-columbia-blue focus:ring-columbia-blue text-columbia-blue' %>
    <%= f.label :password, class: 'mt-4 text-xl' %>
    <%= f.password_field :password, class: 'p-1 border border-gray-600 rounded-lg bg-gray-700 border-gray-600 placeholder-columbia-blue focus:border-columbia-blue focus:ring-columbia-blue text-columbia-blue' %>
    <%= f.submit 'Login', class: 'bg-columbia-blue hover:bg-poly-green text-black hover:text-columbia-blue font-bold py-2 px-4 rounded-lg mt-5' %>
  </div>
<% end %>

app/views/search/index.html.erb
<%= turbo_frame_tag :dropdown_results do %>
  <% if @search_results.present? %>
    <% @search_results.each do |manufacturer, discs| %>
      <%= render DiscPreviewComponent.new(manufacturer:, discs:) %>
    <% end %>
  <% else %>
    <h1 class="text-xl font-bold">No results found</h1>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="flex flex-wrap justify-center md:justify-start px-10 py-5">
  <div class="md:w-1/4">
    <%= link_to root_path do %>
      <%= image_tag('fullWhite.png') %>
    <% end %>
  </div>
</nav>